menu:
  Blog: /
  Tags: /tags
  Weibo: http://weibo.com/1674333040
  twitter: https://twitter.com/hongwei89
  #rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: yihongwei

# Analytics
# google-analytics:
ga: UA-66911097-1

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
