menu:
  Blog: /
  Tags: /tags
  Weibo: http://weibo.com/1674333040
  twitter: https://twitter.com/hongwei89
  #rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus:
duoshuo: yihongwei

# google-analytics:
ga: UA-66911097-1
# baidu-analytics:
ba:
